swagger: "2.0"
info:
  description: "This is a sample greeting server. "
  version: "1.0.0"
  title: "Swagger Petstore"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "vsrp1010@gmail.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost:8080"
basePath: "/"
tags:
- name: "greeting"
  description: "Everything about Greetings"
  externalDocs:
    description: "Find out more"
    url: "http://swagger.io"
schemes:
- "http"
paths:
  /greeting:
    get:
      tags:
      - "greeting"
      summary: "Get a greeting"
      description: "Get a generic or personalized greeting"
      operationId: "getGreeting"
      produces:
      - "application/json"
      parameters:
      - name: "name"
        in: "query"
        description: "Status values that need to be considered for filter"
        required: true
        type: "string"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Greeting"
definitions:
  Greeting:
    type: "object"
    required:
    - "id"
    - "content"
    properties:
      id:
        type: "integer"
        format: "int64"
      content:
        type: "string"
        example: "Hello, User!"
    xml:
      name: "Greeting"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"